language: java
notifications:
  hipchat:
    rooms:
      secure: pcul9XP2fjsehDI3QWFidxXQoG8aWVb44b1sngxCetUUgnbV+C39ku/8zXJya/bQUPyzxKxML4JIKyKltofV6Hrz5Bf2sGMihxH/dVcp2sFBDzx67QqvCMifpR7ALy5/fVcwCmBh8OH206IOVCRN/zNfnR7JU7XssNLSAgCiknCprTl2PZiWi1AYekTxB/Hcwd89CRWaizHwhsWNJKieOUY2gzbbLzBmAx8GffMoCB0NsOX6Jn0J3ECG9jrdyPom2MhDtv5GNgDdd/slKcEH9uPx+pZVL3QfbzMQA59nApiVkzO3tswz3UIxTK2J2i/xL1wxK1/M0En7+4K8II1HiqV2TpLPM7Qxz8qrsy/N3lxNAU4ixpBInURaD+5UDQd3ExH8X/LU/PvQfitP0lT+pvuUXUexrRbGXRA/+FqausCB3dn5Q/o4gd3G05xc+6nCiYhJMyupicReQ4ckjir3AP72kLsPtBHmsVhU/I+J3xfVZzmPxF1T5Ha7FsV3K3PK0+TGIFM4WTO89FdUFAn28hHwUugYs2WLpbQEIqBps/kOS4hBTRoEiRKKkkivUukysUAaeTI75Y3glsO5RwY9ZySE3NltYkyvLhTFv6VGXKoaSmnpJTAlOwaoKag3G13ipQyD+Y3vjrFR1w7cT2KAOEzRc/jgqISHHFB9wBiWlmo=
deploy:
  provider: releases
  api_key:
    secure: e9BWssM4B/8+4YZiEmiSxNtC898ll2zydmO3yN11mrrMbWVCc/akfiVdPQH41wHS83QT0rPk1tIqp9zizou0LHVSJp6xTyMj1pMjmuFsNTdTLfIGx+TusFyz2VqybtpPUwU9faiFdFH/Bs40VRqpWSoIt12gtmMzDbP/1Ve0KUU6QpNaWQv4HFja166KgeVbIwKvr92xD9F0RCxmvuY+fH+kFa7efPso1sUTZaMXPmTO6CtkRsqniHba/hwRLbK2v3Iu5dQ6bxH8ndp+otsfE9UcQsUEnqLCDN01FnG5C665dVNyjLEkxAZN4WRnJEvLg7D0G3NXsim2ddtX7dy+RetaV7XOuZPRn8rNqWBH+U1d1V6Z/q2Xvnyv4HSXqixb9Y1q82Yxn/psx4rifdsd+Bjuw+giohQqCEVzhGxkKDoP9J22Doz5b/TQdqK6FhW5JCePcKqcpsupitfBmpRxYzZGnZ99zEHzrypMQLFffQNSB2SURPhaZso1gPnVv9BayBOY8l3wf7cFB+oowlL4pKH0iylXawH+4hhrUunVuvtHjIAbMXWE8Nshb5h1fZTy/WE39VVsT3WjWfswaW2aC5+Bpf8IRujGrqV3uSdbctFjiH5JzOKtiIhvjSvGTf3idOhK2G8CTXHbsQiZ8q7t1lHZjQ17V5gIjLje0aGh4v8=
  file: build/libs/xld-type-migrator-plugin-4.5.4.jar
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-type-migrator-plugin
